PRODUCTS = [
 dict(slug="quorum", name="Quorum", cat="Workplace", status="In development",
      art="quorum",
      tag="Decision intelligence for operating teams.",
      lede="Every meaningful decision a company makes is argued once, decided once, and then forgotten. Quorum keeps the reasoning.",
      problem="Teams do not lose decisions because nobody made them. They lose them because the context lives in a call nobody recorded, a thread nobody can find, and three people's heads. Six months later the same debate restarts from zero.",
      does=[("Captures the reasoning, not the outcome","It listens to how a decision got made: the constraints, the tradeoffs, the option that was rejected and why."),
            ("Surfaces the precedent before the argument","When a team starts relitigating, Quorum puts the prior decision and its context in front of them first."),
            ("Tracks what the decision assumed","Every decision rests on assumptions. Quorum flags them when the world changes underneath.")]),
 dict(slug="camber", name="Camber", cat="Operations", status="In development",
      art="camber",
      tag="An operations copilot for work that happens in the physical world.",
      lede="Software ate the office long before it touched the warehouse floor. Camber is built for the second one.",
      problem="Operations teams run on exception handling: the shipment that missed, the route that broke, the crew that called out. That work is judgment under time pressure with incomplete information, and almost none of it is written down anywhere a model can learn from.",
      does=[("Reads the exception, not the dashboard","Camber works from the messy signal operators actually get: texts, calls, scans, and half-filled forms."),
            ("Proposes the call and shows its work","Every recommendation arrives with the constraints it weighed, so a dispatcher can overrule it in one glance."),
            ("Learns the local rules","Every operation has conventions that exist nowhere in the SOP. Camber picks them up from how people actually decide.")]),
 dict(slug="understory", name="Understory", cat="Knowledge", status="In development",
      art="understory",
      tag="Turns what an organization knows into something it can be asked.",
      lede="Most companies do not have a knowledge problem. They have a retrieval problem that everyone has quietly given up on.",
      problem="The answer usually exists. It is in a document from two reorgs ago, written by someone who left, using terminology the current team does not use. Search fails because the question and the answer do not share a single word.",
      does=[("Indexes meaning, not keywords","Understory maps how your organization actually talks about its own work, including the terms that changed."),
            ("Answers with provenance","Every answer names its source, its date, and how confident it is that the source is still current."),
            ("Says when it does not know","The most valuable output of a knowledge system is an honest gap. Understory is built to report one.")]),
 dict(slug="tidemark", name="Tidemark", cat="Fintech", status="In development",
      art="tidemark",
      tag="Cash-flow intelligence for businesses that live close to the line.",
      lede="Most small businesses do not fail from bad margins. They fail from good margins and bad timing.",
      problem="A profitable business can still run out of money on a Tuesday. The information needed to see it coming is spread across a bank, a processor, a payroll provider, and an accounting tool that reconciles once a month.",
      does=[("Models the next ninety days, not the last quarter","Tidemark forecasts forward from real transaction flow rather than reporting backward from the ledger."),
            ("Names the specific week that breaks","A forecast is only useful if it points at a date and a cause. Tidemark does both."),
            ("Shows what actually moves the outcome","It ranks the levers by how much they change the forecast, so the smallest useful action is obvious.")]),
]

STEPS = [
 dict(t="We start from a capability, not a category.",
      b="Most products begin with a market and go looking for features. We begin with something models can now do reliably, then hunt for the place that capability collapses an entire workflow instead of decorating one."),
 dict(t="We build the smallest thing that proves it.",
      b="A working product in front of real users in weeks. Not a deck, not a pilot, not a design partner agreement. If the capability does not survive contact with real inputs, we would rather know in week three than in quarter three."),
 dict(t="We design for the failure modes first.",
      b="AI products break differently than software does. They fail confidently. We build the evaluation harness, the fallbacks, and the moments of honest uncertainty before we build the happy path, because those are the product."),
 dict(t="Then we earn the second session.",
      b="Getting someone to try an AI product is easy right now. Getting them back on Wednesday is the entire game. We instrument for return, not for signups, and we keep building until that number moves."),
]

CAREER = [
 ("Microsoft", "Vice President, Azure Experiences and Ecosystems", "The product surface of Azure and its AI surface areas."),
 ("Microsoft", "Head of Global Payments", "Payments infrastructure across Microsoft's consumer and commercial business."),
 ("Pinwheel", "Founder", "A leading fintech API for direct deposit and bill switching."),
 ("Luxe", "Founder", "On-demand parking and valet. Acquired by Volvo."),
 ("Stripe", "Corporate Development", ""),
 ("Groupon", "Vice President, Consumer Products", ""),
 ("Google and YouTube", "Product Management", ""),
 ("Zynga", "Product Management", ""),
]
